name: Continuous Integration

on: 
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    lint:
        name: Lint CI
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses:  actions/checkout@v3

        - name: Setup Python 3.9
          uses: actions/setup-python@v4
          with:
            python-version: 3.9
        
        - name: Install dependencies
          run: |
           python -m pip install --upgrade pip
           pip install ruff
        - name: Run Ruff linter
          run: ruff check .
        

    test:
        name: Run tests
        runs-on: ubuntu-latest
    
        steps:
        - name: Checkout code
          uses:  actions/checkout@v3
        
        - name: Setup Python 3.9
          uses: actions/setup-python@v4
          with:
            python-version: 3.9
    
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
    
        - name: Run tests with pytest
          run: |
            pytest tests/ -v

