name: Docker CI/CD

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    test:
        name: Run tests
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: 3.9

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        
        - name: Run tests
          run: pytest tests/ -v

    build:
        name: Build Docker image
        runs-on: ubuntu-latest
        needs: test

        steps: 
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Build Docker Image
          uses: docker/build-push-action@v4
          with:
            context: .
            push: false
            tags: my-app:latest

        - name: Test Docker Image
          run: 
            docker build -t my-app:test .
            docker run --rm my-app:test python -c "from app import hello_world; print(hello_world())"